def shown_design():
    import turtle as t
    t.forward(50)
    t.left(90)
    t.forward(50)
    t.left(90)
    t.forward(50)
    t.left(90)
    t.forward(50)
    t.penup()
    t.goto(-5,-5)
    t.pendown()
    t.left(90)
    t.forward(60)
    t.left(90)
    t.forward(60)
    t.left(90)
    t.forward(60)
    t.left(90)
    t.forward(60)
    t.penup()
    t.goto(-10,-10)
    t.pendown()
    t.left(90)
    t.forward(70)
    t.left(90)
    t.forward(70)
    t.left(90)
    t.forward(70)
    t.left(90)
    t.forward(70)
    t.penup()
    t.goto(-15,-15)
    t.pendown()
    t.left(90)
    t.forward(80)
    t.left(90)
    t.forward(80)
    t.left(90)
    t.forward(80)
    t.left(90)
    t.forward(80)
    t.penup()
    t.goto(-20,-20)
    t.pendown()
    t.left(90)
    t.forward(90)
    t.left(90)
    t.forward(90)
    t.left(90)
    t.forward(90)
    t.left(90)
    t.forward(90)
    t.hideturtle()

def main():
    shown_design()
    import os
    os.system("pause")

main()

